### ISSUE TITLE
mongodb shell commands are executed before the server is started

### ISSUE THREAD

**Issue by morxa** [Stouts/Stouts.mongodb#23]
If I install mongodb and execute a mongodb shell command in the same play, the play will fail. This is because mongodb is only started after the shell commands are executed.

As an example, the following play fails on hosts where mongodb was not installed previously:

```
- hosts: all
  sudo: yes
  roles:
    - Stouts.mongodb
  vars:
    mongodb_conf_auth: yes
    mongodb_shell:
      admin:
        - 'db.updateUser( \"admin\", {roles: [ \"userAdminAnyDatabase\"], pwd: \"test\" } )'
```

Error message:
```
Failed to connect to 127.0.0.1:27017, reason: errno:111 Connection refused
```

mongodb is not running:
```
$ sudo service mongod status
mongod stop/waiting
```
