### ISSUE TITLE
Mongodb shell with various parameters

### ISSUE THREAD

**Issue by Jrmyy** [Stouts/Stouts.mongodb#29]
Hi,

I noticed this returns me an error:

``` YAML
mongodb_shell:
  database:
    - db.createCollection('table1');
    - db.createCollection('table2');
```

I think this is due to the `item.value|join('\n')`  because when I change `'\n'` to `' '` it works
