### ISSUE TITLE
Ubuntu 16.04 Could not find the requested service mongod: host

### ISSUE THREAD

**Issue by unfii** [Stouts/Stouts.mongodb#36]
When configure almost finish on Ubuntu 16.04 I have such error

TASK [Stouts.mongodb : Ensure mongodb is started] >

`{"changed": false, "failed": true, "msg": "Could not find the requested service mongod: host"}`

my playbook

```
---
- name: Mongodb servers
  hosts: dbservers
  sudo: true
  vars:
    mongodb_conf_replSet: rs1/mongodb-test1:27017,mongodb-test2:27017
    mongodb_shell:
      db-name:
        - rs.initiate()
  roles:
  - Stouts.mongodb

```
